dotfiles-scripts: small adjustments, improve docs

diff --git a/.local/bin/dotfiles-remove b/.local/bin/dotfiles-remove
--- a/.local/bin/dotfiles-remove
+++ b/.local/bin/dotfiles-remove
@@ -6,24 +6,28 @@
 # original location.
 # $1: path of the file/folder to remove. Must be located under the dotfiles repo.
 
+
 # todo: make repo path and config path configurable
-repo_path="$HOME/voidrice"
-dotfiles_config="$repo_path/.dotfiles/mappings_linux.json"
-file_path=$(realpath --relative-to="$repo_path" "$1")
-orig_path=$repo_path/$file_path
-new_path=$HOME/$file_path
+work_dir=$HOME                                               # base path where dotfiles are linked to
+repo_path="$HOME/voidrice"                                   # path to the dotfiles repo
+dotfiles_config="$repo_path/.dotfiles/mappings_linux.json"   # path to the dotfiles mappings file
+file_path=$(realpath --relative-to="$repo_path" "$1")        # provided path relative to $repo_path
+orig_path=$repo_path/$file_path                              # current path of file (in dotfiles repo)
+new_path=$work_dir/$file_path                                # new path of file (replacing symlink)
 
 new_mappings="$(jq "del(.[\"$file_path\"])" < $dotfiles_config)"
+
+
+# validating current symlink pointing to current path of file:
+target=$(readlink -f $new_path)
+if [ $target != $orig_path ]; then
+    echo "ERROR: could not find a symlink at $new_path pointing to $orig_path"
+    exit 2
+fi
 
 echo "removing $file_path from mappings"
 echo "$new_mappings" > $dotfiles_config
 
-target=$(readlink -f $new_path)
-
-if [ $target != $orig_path ]; then
-    echo "could not find a symlink at $new_path pointing to $orig_path"
-    exit 2
-fi
 echo "removing symlink at $new_path"
 rm $new_path
 
