rofi-1password, /etc configs (X11), fix xdg-open for folders

diff --git a/.local/bin/with-secure-env b/.local/bin/with-secure-env
--- a/.local/bin/with-secure-env
+++ b/.local/bin/with-secure-env
@@ -16,9 +16,17 @@
 # // prints 'foo bar':
 # with-secure-env my-command bar
 #
-#
 
-exec_name=$1
+if [[ $# -gt 0 ]]; then
+    # no alias provided:
+    exec_path=$1
+    file_name=$(basename $1)
+else
+    echo "invalid arguments. Usage: with-secure-env <EXEC> [..EXEC_ARGS]"
+    exit 1
+fi
 
-source <(pass show $exec_name)
-exec $exec_name "${@:2}" 
+# echo "exec: $exec_path"
+
+source <(pass show $file_name)
+exec $exec_path "${@:2}" 
